Fix and test gha failing workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,36 +27,26 @@ jobs:
 
       - name: Render and validate all Helm charts
         run: |
+          set -e  # Exit the script if any command fails
+          
           # Find all Helm chart directories and process each one
-          set -e
-          ERROR=false
-          find . -name 'Chart.yaml' -exec dirname {} \; | while read chart_dir; do
+          find . -name 'Chart.yaml' -exec dirname {} \; | while read -r chart_dir; do
             echo "Processing Helm chart in $chart_dir"
-            mkdir -p rendered_templates/$chart_dir
-            if ! helm template $chart_dir --output-dir rendered_templates/$chart_dir; then
-              echo "Helm template failed for $chart_dir"
-              ERROR=true
-            fi
-            if ! find rendered_templates/$chart_dir -name '*.yaml' -exec kubeconform -strict {} +; then
-              echo "kubeconform validation failed for $chart_dir"
-              ERROR=true
-            fi
+            mkdir -p "rendered_templates/$chart_dir"
+          
+            # Render Helm templates and validate
+            echo "Rendering templates for $chart_dir"
+            helm template "$chart_dir" --output-dir "rendered_templates/$chart_dir"
+            echo "Validating rendered templates for $chart_dir"
+            find "rendered_templates/$chart_dir" -name '*.yaml' -exec kubeconform -strict {} +
           done
-          if [ "$ERROR" = true ]; then
-            exit 1
-          fi
 
       - name: Lint all Helm charts
         run: |
-          set -e
-          ERROR=false
-          find . -name 'Chart.yaml' -exec dirname {} \; | while read chart_dir; do
+          set -e  # Exit the script if any command fails
+          
+          # Find all Helm chart directories and lint each one
+          find . -name 'Chart.yaml' -exec dirname {} \; | while read -r chart_dir; do
             echo "Linting Helm chart in $chart_dir"
-            if ! helm lint $chart_dir; then
-              echo "Helm lint failed for $chart_dir"
-              ERROR=true
-            fi
+            helm lint "$chart_dir"
           done
-          if [ "$ERROR" = true ]; then
-            exit 1
-          fi
